// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6KdcFzS7FSQ_8nG5yZ5QzxEu89ckBq4',
    appId: '1:1030513018501:web:71280cadbb7cfb39b90bec',
    messagingSenderId: '1030513018501',
    projectId: 'hunargah-app',
    authDomain: 'hunargah-app.firebaseapp.com',
    storageBucket: 'hunargah-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpJE5NlHL6PpTFb6AIm2jP6bY9zwaUiKc',
    appId: '1:1030513018501:android:f3074806995a8386b90bec',
    messagingSenderId: '1030513018501',
    projectId: 'hunargah-app',
    storageBucket: 'hunargah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAmk8fC1BPtKDSfB-uu6cYPRs0AYMix0',
    appId: '1:1030513018501:ios:04a439409c7bd3fdb90bec',
    messagingSenderId: '1030513018501',
    projectId: 'hunargah-app',
    storageBucket: 'hunargah-app.firebasestorage.app',
    iosBundleId: 'com.example.hunargah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAmk8fC1BPtKDSfB-uu6cYPRs0AYMix0',
    appId: '1:1030513018501:ios:04a439409c7bd3fdb90bec',
    messagingSenderId: '1030513018501',
    projectId: 'hunargah-app',
    storageBucket: 'hunargah-app.firebasestorage.app',
    iosBundleId: 'com.example.hunargah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs6KdcFzS7FSQ_8nG5yZ5QzxEu89ckBq4',
    appId: '1:1030513018501:web:cf0043bdb10818d5b90bec',
    messagingSenderId: '1030513018501',
    projectId: 'hunargah-app',
    authDomain: 'hunargah-app.firebaseapp.com',
    storageBucket: 'hunargah-app.firebasestorage.app',
  );
}
